version: '3'
# docker-compose -f docker-compose.yml up
# 运行单个服务
# docker-compose up <service-name>
services:
  frontend:
    container_name: uniapp
    build: 
      context:  ../src/frontend/
      dockerfile: Dockerfile
    volumes: 
      - ../src/frontend:/frontend
    command: > 
      sh -c "npm install && npm run dev:mp-weixin"

  backend:
    container_name: flask
    build: 
      context:  ../src/backend/
      dockerfile: Dockerfile
    volumes:
      - ../src/backend/app:/backend/app
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000 --debugger --reload"