version: '3'
# docker-compose -f docker-compose.dev.yml up
services:
  uniapp-dev:
    container_name: uniapp-dev
    build: 
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev:mp-weixin"]
