version: '3'
# docker-compose -f docker-compose.dev.yml up
services:
  frontend:
    container_name: uniapp
    build: 
      context:  ../src/frontend/
      dockerfile: ../src/frontend/Dockerfile
    command: > 
      sh -c "npm install && npm run dev:mp-weixin"

  backend:
    container_name: flask
    build: 
      context:  ../src/backend/
      dockerfile: ../src/backend/Dockerfile
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000"