version: '3'
services:
  uniapp-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev:mp-weixin"]
