# Dockerfile.dev
# docker build -t vue-dev -f Dockerfile.dev .
# docker run -it --rm -v $(pwd)/:/app -p 8080:8080 vue-dev
FROM node:lts

WORKDIR '/app'

COPY package.json ./

RUN npm install

CMD ["npm", "run", "dev:mp-weixin"]
