# Dockerfile.dev
# docker build -t vue-dev -f Dockerfile.dev .
# docker run -it --rm -v $(pwd)/:/app -p 8080:8080 vue-dev

FROM node:14

WORKDIR /app

COPY . .

RUN npm install 

CMD ["npm","run","dev:mp-weixin"]